# https://query.wikidata.org/
# anime -> cast_member -> gender
select distinct ?cast_member ?gender

with {    
    SELECT distinct ?anime
    WHERE {
        ?anime wdt:P31/wdt:P279* wd:Q1107 .
    }
} as %q0

with {
    SELECT distinct ?anime ?cast_member
    WHERE {
        include %q0
        ?anime wdt:P161 ?cast_member .
    }
} as %q1

where {
    include %q1
    ?cast_member wdt:P21 ?gender .
}
