# https://query.wikidata.org/
# documentary -.-> director
SELECT distinct ?documentary ?director
with { 
    SELECT distinct ?documentary
    WHERE {
        ?documentary wdt:P31/wdt:P279* wd:Q4164344 .
    }
} as %q0    
WHERE {
    include %q0
    ?documentary wdt:P57 ?director .
}
