# https://query.wikidata.org/
# anime -> capital_cost -> label -> es
SELECT ?capital_cost ?capital_cost_label (lang(?capital_cost_label) as ?language)
with {
    SELECT distinct ?anime
    WHERE {
        ?anime wdt:P31/wdt:P279* wd:Q1107 .
    }
} as %q0
    
with {
    SELECT distinct ?anime ?capital_cost
    WHERE {
        include %q0
        ?anime wdt:P2130 ?capital_cost .
    }
} as %q1
    
with {
    SELECT distinct ?capital_cost
    WHERE {
        include %q1
    }
} as %q

WHERE {
    include %q
    ?capital_cost rdfs:label ?capital_cost_label filter (lang(?capital_cost_label) = "es").
}
