# https://query.wikidata.org/
# documentary -> director -> award_received
select distinct ?director ?award_received

with {    
    SELECT distinct ?documentary
    WHERE {
        ?documentary wdt:P31/wdt:P279* wd:Q4164344 .
    }
} as %q0

with {
    SELECT distinct ?documentary ?director
    WHERE {
        include %q0
        ?documentary wdt:P57 ?director .
    }
} as %q1

where {
    include %q1
    ?director wdt:P166 ?award_received .
}
