# https://query.wikidata.org/
# documentary -> cast_member -> nominated_for
select distinct ?cast_member ?nominated_for

with {    
    SELECT distinct ?documentary
    WHERE {
        ?documentary wdt:P31/wdt:P279* wd:Q4164344 .
    }
} as %q0

with {
    SELECT distinct ?documentary ?cast_member
    WHERE {
        include %q0
        ?documentary wdt:P161 ?cast_member .
    }
} as %q1

where {
    include %q1
    ?cast_member wdt:P1411 ?nominated_for .
}
