# https://query.wikidata.org/
# film -> imdb_id -> label -> es
SELECT ?imdb_id ?imdb_id_label (lang(?imdb_id_label) as ?language)
with {
    SELECT distinct ?film
    WHERE {
        ?film wdt:P31/wdt:P279* wd:Q11424 .
    }
} as %q0
    
with {
    SELECT distinct ?film ?imdb_id
    WHERE {
        include %q0
        ?film wdt:P345 ?imdb_id .
    }
} as %q1
    
with {
    SELECT distinct ?imdb_id
    WHERE {
        include %q1
    }
} as %q

WHERE {
    include %q
    ?imdb_id rdfs:label ?imdb_id_label filter (lang(?imdb_id_label) = "es").
}
