# https://query.wikidata.org/
# documentary -> genre -> label -> en
SELECT ?genre ?genre_label (lang(?genre_label) as ?language)
with {
    SELECT distinct ?documentary
    WHERE {
        ?documentary wdt:P31/wdt:P279* wd:Q4164344 .
    }
} as %q0
    
with {
    SELECT distinct ?documentary ?genre
    WHERE {
        include %q0
        ?documentary wdt:P136 ?genre .
    }
} as %q1
    
with {
    SELECT distinct ?genre
    WHERE {
        include %q1
    }
} as %q

WHERE {
    include %q
    ?genre rdfs:label ?genre_label filter (lang(?genre_label) = "en").
}
