# https://query.wikidata.org/
# film -> director -> occupation
select distinct ?director ?occupation

with {    
    SELECT distinct ?film
    WHERE {
        ?film wdt:P31/wdt:P279* wd:Q11424 .
    }
} as %q0

with {
    SELECT distinct ?film ?director
    WHERE {
        include %q0
        ?film wdt:P57 ?director .
    }
} as %q1

where {
    include %q1
    ?director wdt:P106 ?occupation .
}
