# https://query.wikidata.org/
# film -.-> cast_member
SELECT distinct ?film ?cast_member
with { 
    SELECT distinct ?film
    WHERE {
        ?film wdt:P31/wdt:P279* wd:Q11424 .
    }
} as %q0    
WHERE {
    include %q0
    ?film wdt:P161 ?cast_member .
}
