# https://query.wikidata.org/
# film -.-> genre
SELECT distinct ?film ?genre
with { 
    SELECT distinct ?film
    WHERE {
        ?film wdt:P31/wdt:P279* wd:Q11424 .
    }
} as %q0    
WHERE {
    include %q0
    ?film wdt:P136 ?genre .
}
